apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: f9jgal5vd-go-gitops
  description: This is GitOps manifest for f9jgal5vd-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=f9jgal5vd-go
    backstage.io/kubernetes-id: f9jgal5vd-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: f9jgal5vd-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:f9jgal5vd-go
